### ISSUE TITLE
ATM8 Crashing

### ISSUE THREAD

**Issue by GianBala83** [AllTheMods/ATM-8#800]
I started a world in All the Mods 8-1.0.9 and the game crashes a lot of times even i haven't done anything considerable, i hope it is fixed quickly, so i can play with my friends without problems

The crashlogs:
https://mclo.gs/PXQUBmN
https://mclo.gs/Nqj5pxG

**Comment by Mitchell5200** [comment]
Can't fix any crashes without the crashlogs to identify causes.

Upload your full Crashlog via https://mclo.gs/ and share the link back here.

**Comment by GianBala83** [comment]
I updated the message with the crashlog

**Comment by Mitchell5200** [comment]
ok, looks like that crash is fixed in AE2things v1.1.1, we'll have that in the next pack update in a day or so.

**Comment by GianBala83** [comment]
Thank you for your attention, cant wait for the update

**Comment by GianBala83** [comment]
I tried to exchange the AE2things 1.1.0 to the new version (1.1.1) but it still crashes

Crashlog:
https://mclo.gs/Q6pVZ42

**Comment by Mitchell5200** [comment]
> I tried to exchange the AE2things 1.1.0 to the new version (1.1.1) but it still crashes
> 
> Crashlog: https://mclo.gs/Q6pVZ42

That's the Legacy Random Source crash, that'll also be fixed in 1.0.10 of the pack soon ish
or just update evilcraft in the meantime

**Comment by Mitchell5200** [comment]
Fixed in 1.0.10 (i hope)
